name             'apache_exercise'
maintainer       'David Hayden'
maintainer_email 'talosthoren@gmail.com'
license          'All rights reserved'
description      'Updates apache configurations'
long_description 'Used to perform a rotating update, one node at a time.'
version          '0.1.0'
